const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
window.addEventListener("load",()=>{let p=0;const bar=$("#loaderBar"),pct=$("#loaderPct");const t=setInterval(()=>{p+=Math.floor(Math.random()*9)+4;if(p>=100){p=100;clearInterval(t);setTimeout(()=>$("#loader").classList.add("hide"),350)}bar.style.width=p+"%";pct.textContent=p+"%"},90)});
const canvas=$("#stars"),ctx=canvas.getContext("2d");let stars=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;stars=Array.from({length:150},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*1.4+.2,a:Math.random()}))}resize();addEventListener("resize",resize);function starLoop(){ctx.clearRect(0,0,canvas.width,canvas.height);stars.forEach(s=>{s.a+=.005;ctx.globalAlpha=.3+Math.sin(s.a)*.3;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(starLoop)}starLoop();
$("#menuBtn").onclick=()=>$("#navLinks").classList.toggle("open");$$("nav a").forEach(a=>a.onclick=()=>$("#navLinks").classList.remove("open"));
const cursorDot=$("#cursorDot"),cursorRing=$("#cursorRing");addEventListener("mousemove",e=>{cursorDot.style.left=e.clientX+"px";cursorDot.style.top=e.clientY+"px";cursorRing.style.left=e.clientX+"px";cursorRing.style.top=e.clientY+"px"});
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});$$(".reveal").forEach(x=>obs.observe(x));
$$(".journey-stage").forEach((x,i)=>x.onclick=()=>{const data=[["EARTH LAUNCH","The mission begins with a controlled ascent through Earth's atmosphere.","0 KM"],["LUNAR WINDOW","A carefully timed lunar pass changes the vehicle's trajectory.","384,000 KM"],["DEEP SPACE","The spacecraft enters a quiet cruise phase between worlds.","82M KM"],["MARS ORBIT","The vehicle performs orbital insertion and prepares for descent.","225M KM"],["DESCENT","Atmospheric entry, parachutes and powered descent begin.","225M KM"],["SURFACE OPERATIONS","Touchdown. The mission becomes an exploration.","225M KM"]][i];$$(".journey-stage").forEach(z=>z.classList.remove("active"));x.classList.add("active");$("#phaseNo").textContent="PHASE "+String(i+1).padStart(2,"0");$("#phaseTitle").textContent=data[0];$("#phaseText").textContent=data[1];$("#phaseDistance").textContent=data[2];$("#routeProgress").style.width=((i/5)*100)+"%"});
let launched=false;$("#launchBtn").onclick=()=>{if(launched)return;launched=true;let n=10;const cd=$("#countdown"),state=$("#launchState"),r=$("#rocketWrap");const t=setInterval(()=>{n--;cd.textContent="T−"+n;if(n<=0){clearInterval(t);cd.textContent="LIFTOFF";state.textContent="ASCENT CONFIRMED";r.classList.add("launching");setTimeout(()=>{r.classList.remove("launching");state.textContent="ORBIT ACHIEVED"},3200)}},700)};
let telemetryTick=0;setInterval(()=>{telemetryTick++;$("#velocity").textContent=(24781+Math.sin(telemetryTick/5)*180|0).toLocaleString();$("#fuel").textContent=Math.max(70,87-telemetryTick%18);$("#signal").textContent=94+telemetryTick%6;$("#radiation").textContent=(.42+Math.sin(telemetryTick/8)*.04).toFixed(2);$("#hullTemp").textContent=21+telemetryTick%4;$("#solar").textContent=90+telemetryTick%7;},1100);
const roverText={ "NAV CAMERA":["NAV CAMERA","Panoramic cameras create a 360° map of the terrain."],"DRILL ARM":["DRILL ARM","A robotic drill collects protected subsurface samples."],"SPECTROMETER":["SPECTROMETER","Laser spectroscopy identifies minerals from a safe distance."]};$$(".hotspot").forEach(b=>b.onclick=()=>{let a=roverText[b.dataset.title];$("#hotspotInfo").innerHTML=`<span>ROVER SYSTEM</span><h3>${a[0]}</h3><p>${a[1]}</p>`});
$$(".weather-btn").forEach(b=>b.onclick=()=>{let d={clear:["☀","CLEAR SKIES","Low dust · visibility 90 km","−63°C","18 KM/H","90 KM"],dust:["〰","DUST FRONT","Fine dust · visibility 20 km","−58°C","46 KM/H","20 KM"],storm:["⚠","GLOBAL STORM","Severe dust · visibility 2 km","−71°C","110 KM/H","2 KM"],cold:["❄","COLD NIGHT","Surface frost · visibility 75 km","−96°C","7 KM/H","75 KM"]}[b.dataset.weather];$$(".weather-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#weatherVisual").className="weather-visual reveal visible "+b.dataset.weather;$("#weatherIcon").textContent=d[0];$("#weatherName").textContent=d[1];$("#weatherDesc").textContent=d[2];$("#wTemp").textContent=d[3];$("#wWind").textContent=d[4];$("#wVis").textContent=d[5]});
const sampleData={SOIL:["ORGANIC SIGNATURES DETECTED","Complex carbon-bearing molecules found. Further drilling recommended."],ICE:["WATER ICE CONFIRMED","Hydrogen-oxygen signature consistent with subsurface water ice."],ROCK:["ANCIENT MINERALS FOUND","Mineral layering suggests a long history of liquid-water interaction."],ATMOSPHERE:["TRACE GASES ISOLATED","Atmospheric sample contains CO₂ with trace methane fluctuations."]};$$(".sample").forEach(b=>b.onclick=()=>{let d=sampleData[b.dataset.sample];$$(".sample").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#sampleStatus").textContent="SAMPLE "+b.dataset.sample+" // READY";$("#sampleResult").textContent=d[0];$("#sampleText").textContent=d[1]});$("#analyzeBtn").onclick=()=>{const s=$("#sampleStatus");s.textContent="ANALYZING // SCANNING";$("#sampleOrb").style.transform="scale(1.15)";setTimeout(()=>{s.textContent="ANALYSIS COMPLETE // VERIFIED";$("#sampleOrb").style.transform=""},1800)};
$("#sendBtn").onclick=()=>{const btn=$("#sendBtn"),packet=$("#signalPacket"),msg=$("#messageInput").value||"HELLO, MARS";$("#messageStatus").textContent=`TRANSMITTING “${msg.toUpperCase()}” · SIMULATED 12m 34s DELAY`;packet.style.opacity=1;packet.style.transition="left 3s linear";packet.style.left="100%";setTimeout(()=>{packet.style.left="0";packet.style.opacity=0;$("#messageStatus").textContent="MESSAGE RECEIVED ON MARS · ACKNOWLEDGEMENT RETURNING"},3200)};
const crewRoles={COMMANDER:"Leads surface decisions, EVA planning and mission priorities.",PILOT:"Owns navigation, landing sequence and spacecraft flight systems.",ENGINEER:"Keeps power, habitat, tools and emergency systems operational.",SCIENTIST:"Studies geology, samples and the search for ancient biosignatures."};$$(".crew-card").forEach(c=>c.onclick=()=>{$("#crewDetail").innerHTML=`<span>CREW ROLE</span><b>${c.dataset.role}</b><p>${crewRoles[c.dataset.role]}</p>`});
let modules=new Set();$$(".base-row button").forEach(b=>b.onclick=()=>{const m=b.dataset.module;if(modules.has(m))return;modules.add(m);b.classList.add("active");b.textContent="ONLINE";const map={power:"m-power",hab:"m-hab",lab:"m-lab",green:"m-green",comms:"m-comms"};$("."+map[m]).classList.add("on");const score=modules.size*20;$("#baseScore").textContent=score+"%";$("#baseBar").style.width=score+"%"});
let marsSeconds=17*3600+42*60+8;setInterval(()=>{marsSeconds=(marsSeconds+1)%88775;let h=Math.floor(marsSeconds/3600),m=Math.floor(marsSeconds%3600/60),s=marsSeconds%60;$("#marsTime").textContent=[h,m,s].map(x=>String(x).padStart(2,"0")).join(":")},1000);
$("#scoreBtn").onclick=()=>{let score=Math.min(100,35+(launched?20:0)+modules.size*8+($(".sample.active")?15:0)+($(".hotspot-info h3").textContent!=="Select a hotspot"?10:0));$("#missionScore").textContent=score+"%";$("#missionGrade").textContent=score>=90?"MISSION COMMANDER — APPROVED":score>=70?"EXPLORER CLASS — READY":"TRAINEE — COMPLETE MORE OBJECTIVES"};$("#topBtn").onclick=()=>scrollTo({top:0,behavior:"smooth"});
let audioCtx;$("#soundBtn").onclick=()=>{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=90;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.03,audioCtx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.4);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.45);$("#soundBtn").textContent="◉ SOUND ON";setTimeout(()=>$("#soundBtn").textContent="◉ SOUND OFF",1000)};
document.addEventListener("keydown",e=>{if(e.key.toLowerCase()==="m"){document.body.animate([{filter:"brightness(1)"},{filter:"brightness(1.8)"},{filter:"brightness(1)"}],500);alert("CLASSIFIED TRANSMISSION: MARS IS WAITING.")}});

/* ULTIMATE EXPANSION INTERACTIONS */
addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('#scrollProgress').style.width=(h?scrollY/h*100:0)+'%';});

// Mission map follows the journey phase
const mapPhases=['EARTH DEPARTURE','LUNAR WINDOW','DEEP SPACE CRUISE','MARS ORBIT','DESCENT SEQUENCE','SURFACE OPERATIONS'];
const mapDistances=['0 KM','384,000 KM','82,000,000 KM','225,000,000 KM','225,000,000 KM','225,000,000 KM'];
$$('.journey-stage').forEach((x,i)=>x.addEventListener('click',()=>{if($('#mapPhase'))$('#mapPhase').textContent=mapPhases[i];if($('#mapDistance'))$('#mapDistance').textContent=mapDistances[i]}));

// Archive viewer
const viewer=$('#photoViewer'), viewerArt=$('#viewerArt');
$$('.photo-card').forEach(card=>card.addEventListener('click',()=>{const name=card.dataset.photo;$('#viewerTitle').textContent=name;$('#viewerCaption').textContent=card.dataset.caption;viewerArt.className='viewer-art viewer-'+({"OLYMPUS MONS":"olympus","VALLES MARINERIS":"canyon","JEZERO DELTA":"delta","MARS AT NIGHT":"night"}[name]||'night');viewer.classList.add('open')}));
$('#viewerClose').onclick=()=>viewer.classList.remove('open');viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.classList.remove('open')});

// Survival systems slowly fluctuate like live telemetry
const survival={oxygen:92,water:78,rad:96,power:84,thermal:89};
function setMeter(name,val){const cap=name[0].toUpperCase()+name.slice(1);$('#'+name+'Val').textContent=val+'%';$('#'+name+'Bar').style.width=val+'%';}
setInterval(()=>{survival.oxygen=Math.max(86,Math.min(97,survival.oxygen+(Math.random()>.55?1:-1)));survival.water=Math.max(70,Math.min(88,survival.water+(Math.random()>.6?1:-1)));survival.rad=Math.max(91,Math.min(99,survival.rad+(Math.random()>.5?1:-1)));survival.power=Math.max(76,Math.min(92,survival.power+(Math.random()>.55?1:-1)));survival.thermal=Math.max(82,Math.min(95,survival.thermal+(Math.random()>.5?1:-1)));Object.entries(survival).forEach(([k,v])=>setMeter(k,v));},2400);

// Compass reacts to pointer position
const compass=$('#compass');compass.addEventListener('mousemove',e=>{const r=compass.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2);let deg=(Math.atan2(x,-y)*180/Math.PI+360)%360;$('#bearing').textContent=String(Math.round(deg)).padStart(3,'0')+'°';$('#bearingTarget').textContent=deg<45||deg>=315?'MARS BASE':deg<135?'ROVER ATLAS':deg<225?'LANDING ZONE':'EARTH RELAY';$('.compass-needle').style.transform=`rotate(${deg}deg)`});

// Mission achievement system
const badges={first:false,explorer:false,builder:false,life:false,commander:false};
function unlockBadge(id){if(badges[id])return;badges[id]=true;const el=$(`.badge-card[data-badge="${id}"]`);if(el){el.classList.remove('locked');el.classList.add('unlocked');}}
$('#sendBtn').addEventListener('click',()=>unlockBadge('first'));
$$('.hotspot').forEach(x=>x.addEventListener('click',()=>unlockBadge('explorer')));
$$('.base-row button').forEach(x=>x.addEventListener('click',()=>{setTimeout(()=>{if(modules.size===5)unlockBadge('builder')},50)}));
$('#analyzeBtn').addEventListener('click',()=>{unlockBadge('life')});
$('#scoreBtn').addEventListener('click',()=>{setTimeout(()=>{const score=parseInt($('#missionScore').textContent)||0;if(score>=90)unlockBadge('commander')},30)});

// Unlock a few badges automatically if the page is refreshed after completing objectives
if(launched)unlockBadge('commander');
